name: CI UWP

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Build app
      run: msbuild .\SimpleVSUnitTest\SimpleVSUnitTest.sln
      
    - name: VSTest
      run: vstest.console.exe /Platform:x86 .\Debug\UnitTest1.dll


